CREATE DATABASE PROJETO02;
SHOW DATABASES;
USE PROJETO02;

DROP TABLE RELATORIO;
DROP TABLE CATRACA;
DROP TABLE ALUNOS;

SHOW TABLES;

CREATE TABLE ALUNOS (
    MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR (15) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    ALTURA INT NOT NULL,
    PESO INT NOT NULL
);

SELECT * FROM ALUNOS;
TRUNCATE ALUNOS;

CREATE TABLE CATRACA (
	ID_CATRACA INT AUTO_INCREMENT PRIMARY KEY,
	ID_ALUNO INT NOT NULL,
	HORARIO_INICIO DATE NOT NULL,
    HORARIO_SAIDA DATE NOT NULL,
    DURACAO DATE NOT NULL,
    CONSTRAINT FK_ID_ALUNO
		FOREIGN KEY (ID_ALUNO)
        REFERENCES ALUNOS (MATRICULA)
);

SELECT * FROM CATRACA;
TRUNCATE CATRACA;

CREATE TABLE RELATORIO (
    ID_RELATORIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUNO INT NOT NULL,
    HORAS_TOTAIS INT NOT NULL DEFAULT '0',
    HORAS_SEMANAIS INT NOT NULL DEFAULT '0',
    CLASSIFICACAO VARCHAR(50) NOT NULL,
    CONSTRAINT FK_ID_ALUNO_REL
        FOREIGN KEY (ID_ALUNO)
        REFERENCES ALUNOS(MATRICULA)
); 

SELECT * FROM RELATORIO;
TRUNCATE RELATORIO;

