CREATE DATABASE PROJETO02;
USE PROJETO02;

CREATE TABLE ALUNOS (
    MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR (15) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ALTURA INT NOT NULL,
    PESO INT NOT NULL
);

SELECT * FROM ALUNOS;

TRUNCATE ALUNOS;
